# Generated by Django 4.1.3 on 2022-12-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="User",
            new_name="user",
        ),
    ]
