# Generated by Django 4.1.3 on 2022-12-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_user_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
