# Generated by Django 4.1.3 on 2022-12-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="profile1.png", null=True, upload_to=""
            ),
        ),
    ]
